### ISSUE TITLE
Fail to get the correct predicted SMILES

### ISSUE THREAD

**Issue by sunys-pki** [Kohulan/DECIMER-Image_Transformer#18]
Hi,
It would be appreciated if you could kindly share any suggestions with me for my issue below. 

When I run the below decimer command below, I could not get a correct SMILES result, or sometimes, it runs into errors.
And I am running it on a Windows 10 machine.

PS C:\Git\DECIMER-Image_Transformer> decimer --model Canonical --image Sample_Images/caffeine.png
Traceback (most recent call last):
  File "C:\Users\SS\AppData\Local\Programs\Python\Python37\Scripts\decimer-script.py", line 33, in <module>
    sys.exit(load_entry_point('decimer', 'console_scripts', 'decimer')())
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 74, in main
    get_SMILES = predict_SMILES(sys.argv[4])
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 167, in predict_SMILES
    predicted_SELFIES = evaluate(image_path)
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 159, in evaluate
    result.append(SELFIES_tokenizer.index_word[int(predicted_id)])
KeyError: 36

PS C:\Git\DECIMER-Image_Transformer> decimer --model Canonical --image Sample_Images/caffeine.png
Predicted SMILES for Sample_Images/caffeine.png :FF

PS C:\Git\DECIMER-Image_Transformer> decimer --model Canonical --image Sample_Images/caffeine.png
Traceback (most recent call last):
  File "C:\Users\SS\AppData\Local\Programs\Python\Python37\Scripts\decimer-script.py", line 33, in <module>
    sys.exit(load_entry_point('decimer', 'console_scripts', 'decimer')())
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 74, in main
    get_SMILES = predict_SMILES(sys.argv[4])
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 167, in predict_SMILES
    predicted_SELFIES = evaluate(image_path)
  File "c:\Git\decimer-image_transformer\src\decimer\cli.py", line 159, in evaluate
    result.append(SELFIES_tokenizer.index_word[int(predicted_id)])

**Comment by Kohulan** [comment]
Hello,

Please try to install decimer directly from the GitHub repository. Then try again looks like it is a key problem in SELFIES. Also, I would strongly recommend using the Linux subsystem in windows.

pip install git+https://github.com/Kohulan/DECIMER-Image_Transformer.git

- Kohulan
