### ISSUE TITLE
ValueError: Could not find matching concrete function to call loaded from the SavedModel.

### ISSUE THREAD

**Issue by OBrink** [Kohulan/DECIMER-Image_Transformer#46]
It seems like something is fundamentally broken. I'm running it in the WSL on Windows 11 in a Python 3.8 environment.

When I run
```
from DECIMER import predict_SMILES
predict_SMILES("ethyl.png")
```

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/otto/.local/lib/python3.8/site-packages/DECIMER/decimer.py", line 110, in predict_SMILES
    predicted_tokens = DECIMER_V2(chemical_structure)
  File "/home/otto/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 704, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/otto/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/otto/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 295, in restored_function_body
    raise ValueError(
ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * <tf.Tensor 'Decoded_Image:0' shape=(512, 512, 3) dtype=float32>
  Keyword arguments: {}

 Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (1 total):
    * TensorSpec(shape=(299, 299, 3), dtype=tf.float32, name='Decoded_Image')
  Keyword arguments: {}
```

**Comment by OBrink** [comment]
For anyone who has this issue in the future:

delete the directory `~/.data/DECIMER-V2`, then run everything again
